# Generated by Django 5.1.4 on 2024-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('general_statistics', 'Общая статистика'), ('demand', 'Востребованность'), ('geography', 'География'), ('skills', 'Навыки'), ('last_vacancies', 'Последние вакансии')], default='general_statistics', max_length=50),
        ),
    ]
