# Generated by Django 5.1.4 on 2024-12-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_report_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('page', models.CharField(choices=[('index_page', 'Главная страница'), ('general_statistics', 'Общая статистика'), ('demand', 'Востребованность'), ('geography', 'География'), ('skills', 'Навыки'), ('last_vacancies', 'Последние вакансии')], default='index_page', max_length=50)),
            ],
        ),
    ]
